weights_path: weights/5fgl4ltv/checkpoints/last.ckpt
config_path: weights/5fgl4ltv/fit_config.yaml
debug_path: debug/
debug_freq: 1.0
flags: []
restart_path: restart_files/warmstart_param.nc
nsteps: 30