mid: 5fgl4ltv
weights_path: weights/${mid}/checkpoints/last.ckpt
config_path: weights/${mid}/fit_config.yaml
debug_path: debug/
debug_freq: 0.0
flags: []
restart_path: restart_files/warmstart_param.nc
halos: 40
nsteps: 1000 
xios_debug: True
